version: 2

models:
  - name: stg_addresses
    description: Addresses from our clients
    columns:
      - name: address_id
        tests:
          - not_null
      - name: address
        tests:
          - not_null
      - name: zipcode
        tests:
          - not_null
      - name: state
        tests: 
          - not_null
      - name: country
        tests: 
          - not_null
  - name: stg_events
    description: Interactions of our clients with the web page (add to cart, page view, etc.)
    columns:
      - name: event_id
        tests: 
          - not_null
      - name: session_id
        tests: 
          - not_null
      - name: user_id
        tests: 
          - not_null
      - name: page_url
        tests: 
          - not_null
      - name: created_at
        tests: 
          - not_null
      - name: event_type
        tests: 
          - not_null
  - name: stg_order_items
    description: Product and quantity of each order
    columns:
      - name: order_id
        tests: 
          - not_null
      - name: product_id
        tests: 
          - not_null
      - name: quantity
        tests: 
          - not_null
  - name: stg_orders
    description: Information from each order
    columns:
      - name: order_id
        tests: 
          - not_null
      - name: user_id
        tests: 
          - not_null
      - name: address_id
        tests: 
          - not_null
      - name: created_at
        tests: 
          - not_null
      - name: order_cost
        tests: 
          - not_null
      - name: shipping_cost
        tests: 
          - not_null
      - name: order_total
        tests: 
          - not_null
      - name: status
        tests: 
          - not_null
  - name: stg_products
    description: Product name, price and inventory
    columns:
      - name: product_id
        tests: 
          - not_null
      - name: name
        tests: 
          - not_null
      - name: price
        tests: 
          - not_null
      - name: inventory
        tests: 
          - not_null
  - name: stg_promos
    description: promo discount and status
    columns:
      - name: promo_id
        tests: 
          - not_null
      - name: discount
        tests: 
          - not_null
      - name: status
        tests: 
          - not_null
  - name: stg_users
    description: user data
    columns:
      - name: user_id
        tests: 
          - not_null
      - name: first_name
        tests: 
          - not_null
      - name: last_name
        tests: 
          - not_null
      - name: email
        tests: 
          - not_null