version: 2

models:
  - name: dim_products
    description: Descriptions of products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique
      - name: product_name
        tests:
          - not_null
      - name: price
        tests:
          - not_null
          - positive_values
      - name: inventory
        tests: 
          - not_null
          - positive_values
  - name: dim_users
    description: Information of our users
    columns:
      - name: user_id
        tests: 
          - not_null
          - unique
      - name: first_name
        tests: 
          - not_null
      - name: last_name
        tests: 
          - not_null
      - name: email
        tests: 
          - not_null
      - name: phone_number
        tests: 
          - not_null
      - name: user_created_at
        tests: 
          - not_null
      - name: address_id
        tests: 
          - not_null
      - name: address
        tests: 
          - not_null
      - name: zipcode
        tests: 
          - not_null
      - name: state
        tests: 
          - not_null
      - name: country
        tests: 
          - not_null
  - name: fact_orders
    description: Information about orders
    columns:
      - name: product_price
        tests:
          - positive_values

